-- 1. Getting information about the crime scene based on the information given
SELECT * FROM crime_scene_reports WHERE day = 28 AND month = 7 AND year = 2020;

-- 2. Using the interviews table to get to know where to look next
SELECT * FROM interviews WHERE day = 28 AND month = 7 AND year = 2020;

-- 3. Eugene mentioned that the theif was withdrawing money from an ATM at Fifer Street before the theft. Therefore I decided to look up the transactions
SELECT * FROM atm_transactions WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020;

-- 4. After obtaining the account number using the previous query, I will gather more information about the bank account
SELECT * FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020; 

-- 5. Using the details I have obtained, I will make a list of names
SELECT * FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020);

-- 6. Now, I will access the exited cars from the courthouse security logs using the license numbers I have
SELECT * FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020));

-- 7. Now I have shortlisted 5 plates and I will access their names Now
SELECT * FROM people WHERE license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020)));

-- 8. I have now made sure that the culprit is among Elizabeth, madison, Danielle, Russell and Ernest. Now i will track their flight data 
SELECT * FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020))));

-- 9. Having obtained the flight ID, I will access the flights on 29th according to what raymond said in the interview
SELECT * FROM flights WHERE day = 29 AND month = 7 AND year = 2020 AND id IN (SELECT flight_id FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020)))));

-- 10. culprit has an id of 18 or 36 --> But I am sure that He has an id of 36 as the flight leaves early in the morning as stated in the interviews. The culprit starts from origin_airport_id = 8 and reaches destination_airport_id = 4, so I used this commmand to infer that 4 is London
SELECT * FROM airports WHERE id = 4;

-- 11. Now I will narrow down my list of passport numbers
SELECT * FROM passengers JOIN flights ON passengers.flight_id = flights.id WHERE id = 36 AND passport_number IN (SELECT passport_number FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020))))) AND seat IN (SELECT seat FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020)))));

-- 12. Gathering details of all suspects using passport numbers tells me that the suspect is either Madison, Danielle OR Earnest
SELECT * FROM people WHERE passport_number IN (SELECT passport_number FROM passengers JOIN flights ON passengers.flight_id = flights.id WHERE id = 36 AND passport_number IN (SELECT passport_number FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020))))) AND seat IN (SELECT seat FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020))))));

-- 13. After checking the calls I can say that either madison or earnest is the culprit
SELECT * FROM phone_calls WHERE duration < 60 AND caller IN (SELECT phone_number FROM people WHERE passport_number IN (SELECT passport_number FROM passengers JOIN flights ON passengers.flight_id = flights.id WHERE id = 36 AND passport_number IN (SELECT passport_number FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020))))) AND seat IN (SELECT seat FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020)))))));

-- 14. When i compare the security logs, I can say that ERNEST IS THE CULPRIT. This is because, according to the interview he left the place in approx. 10 mins after the theft which took place at 10:15 am as opposed to madison who takes a longer time
SELECT * FROM courthouse_security_logs WHERE license_plate IN (SELECT license_plate FROM people WHERE passport_number IN (SELECT passport_number FROM passengers JOIN flights ON passengers.flight_id = flights.id WHERE id = 36 AND passport_number IN (SELECT passport_number FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020))))) AND seat IN (SELECT seat FROM passengers WHERE passport_number IN (SELECT passport_number FROM people WHERE license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day = 28 AND month = 7 AND year = 2020 AND activity = 'exit' AND license_plate IN (SELECT license_plate FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id WHERE person_id in (SELECT person_id FROM bank_accounts JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE transaction_type = 'withdraw' AND atm_location = 'Fifer Street' AND day = 28 AND month = 7 AND year = 2020)))))));

--15. Now, we will find the accomplice's number
SELECT * FROM phone_calls WHERE duration < 60 AND day = 28 AND month = 7 AND year = 2020 AND caller IN (SELECT phone_number FROM people WHERE name = 'Ernest');

--16. Now, we will find the accomplice's name
SELECT name FROM people WHERE phone_number = (SELECT receiver FROM phone_calls WHERE duration < 60 AND day = 28 AND month = 7 AND year = 2020 AND caller IN (SELECT phone_number FROM people WHERE name = 'Ernest'));

-- THEREFORE BERTHOLD IS THE ACCOMPLICE